[package]
name = "rust_fib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "offer"
path = "src/bin/offer.rs"

[[bin]]
name = "answer"
path = "src/bin/answer.rs"

[dependencies]
tokio = "1.47.1"
webrtc = "0.13.0"
base64ct = "=1.6.0"
bytes = "1.10"